sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t weirdoal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true weirdoal/react-test npm test -- --coverage

after_success:
  - docker build -t weirdoal/multi-client ./client
  - docker build -t weirdoal/multi-nginx ./nginx
  - docker build -t weirdoal/multi-server ./server
  - docker build -t weirdoal/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push weirdoal/multi-client
  - docker push weirdoal/multi-nginx
  - docker push weirdoal/multi-server
  - docker push weirdoal/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "Multi-Docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-864166960834"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
